name: adapty_flutter_example
description: Demonstrates how to use the adapty_flutter plugin.
version: 2.10.3
publish_to: none

environment:
  sdk: ">=2.12.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  adapty_flutter:
    path: ../

  cupertino_icons: ^1.0.2
  shared_preferences: ^2.0.15
  uuid: ^3.0.4
  intl: ^0.17.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: false

  assets:
    - assets/
